language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - 3.8-dev
  - pypy
  - pypy3.5
install:
  - pip list
script:
  - python setup.py test
matrix:
  allow_failures:
    - python: 3.8-dev pypy pypy3.5
sudo: false
